import { spawn } from 'node:child_process';

export interface CommandResult {
  exitCode: number | null;
  stderr: string;
  stdout: string;
}

export type CommandRunner = (command: string, args: string[]) => Promise<CommandResult>;

/** Spawns `command` and buffers its output. The suite's only route to the real Docker CLI. */
export function run(command: string, args: string[]): Promise<CommandResult> {
  return new Promise((resolveResult, reject) => {
    const child = spawn(command, args, { stdio: ['ignore', 'pipe', 'pipe'] });
    let stdout = '';
    let stderr = '';
    child.stdout.on('data', (chunk: Buffer) => { stdout += chunk; });
    child.stderr.on('data', (chunk: Buffer) => { stderr += chunk; });
    child.once('error', reject);
    child.once('close', (exitCode) => resolveResult({ exitCode, stdout, stderr }));
  });
}

/**
 * Marks a Docker object as belonging to this suite. Every sweep below filters on
 * it, so nothing unlabelled can be removed -- developer machines run this suite
 * alongside unrelated containers (pgadmin, mariadb, the workspace's own compose
 * stack), and a blanket `docker system prune` would take those out with it.
 */
export const FIXTURE_LABEL = 'eow-fixture';

/** Creation time in epoch milliseconds, so a sweep can tell garbage from a live fixture. */
export const FIXTURE_CREATED_LABEL = 'eow-fixture-created';

/** Compose stamps this on everything it creates; it is how a stale project's volumes are found. */
export const COMPOSE_PROJECT_LABEL = 'com.docker.compose.project';

/**
 * Name prefix shared by every Docker object this suite creates, and generated by
 * nothing else on a developer machine. It is the only handle on objects left by
 * a run that predates the fixture labels, and on a Compose project whose
 * containers are already gone -- one such volume and six such networks, aged
 * between one and nine days, were still on the machine this was written for.
 *
 * Only volumes and networks are swept by name. Docker refuses to remove either
 * while a container still uses it, so a concurrently running copy of this suite
 * protects its own live objects; a container has no such protection, and stays
 * label- and age-gated.
 */
export const FIXTURE_NAME_PREFIX = 'eow_cp1_';

/** Compose project prefix. Every Compose fixture project is `<prefix><random suffix>`. */
export const COMPOSE_PROJECT_PREFIX = `${FIXTURE_NAME_PREFIX}legacy_`;

/**
 * A fixture container outlives its test by at most the longest per-test timeout
 * in this suite (180s) plus container startup, so anything older is garbage from
 * a run that was killed outright. The margin matters: the sweep must not assume
 * it is the only copy of this suite on the machine, and a concurrently running
 * copy's containers are always far younger than this.
 */
export const STALE_FIXTURE_AGE_MS = 15 * 60_000;

/** `docker run` / `docker network create` arguments that stamp both fixture labels. */
export function fixtureLabelArguments(createdAt: number = Date.now()): string[] {
  return ['--label', `${FIXTURE_LABEL}=1`, '--label', `${FIXTURE_CREATED_LABEL}=${createdAt}`];
}

interface TrackedFixture {
  readonly description: string;
  readonly release: () => Promise<void>;
}

const trackedFixtures = new Map<object, TrackedFixture>();

/**
 * Records a live fixture so a test that never reaches its own teardown cannot
 * leak it. Vitest kills a timed-out test outright: the body is abandoned
 * mid-await and the cleanup after it never runs, so one timeout leaves a running
 * container and an orphaned data volume behind permanently. `afterEach` still
 * runs after a kill, so the registry -- not the test body -- is what actually
 * guarantees removal.
 */
export function trackFixture(key: object, description: string, release: () => Promise<void>): void {
  trackedFixtures.set(key, { description, release });
}

/** Hands teardown back to the caller, which is about to remove the fixture itself. */
export function releaseFixture(key: object): void {
  trackedFixtures.delete(key);
}

/** Fixtures the registry currently owns. Zero between tests unless one was abandoned. */
export function trackedFixtureCount(): number {
  return trackedFixtures.size;
}

/**
 * Removes every fixture whose test finished without releasing it, and reports
 * what it took. A non-empty result always means a test was killed mid-fixture.
 */
export async function sweepTrackedFixtures(): Promise<string[]> {
  const abandoned = [...trackedFixtures.values()];
  trackedFixtures.clear();

  const swept: string[] = [];
  for (const fixture of abandoned) {
    try {
      await fixture.release();
      swept.push(fixture.description);
    } catch (error) {
      // The abandoned test body may still be racing the same teardown, so a
      // failure here is usually "already gone". Report it rather than hide it;
      // the killed test has already failed the run on its own.
      const detail = error instanceof Error ? error.message : String(error);
      swept.push(`${fixture.description} (cleanup reported: ${detail})`);
    }
  }
  return swept;
}

interface LabelledObject {
  readonly composeProject: string;
  readonly createdAt: number;
  readonly name: string;
}

function parseLabelledObjects(stdout: string): LabelledObject[] {
  return stdout
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line !== '')
    .map((line) => {
      const [name = '', createdAt = '', composeProject = ''] = line.split('\t');
      return { composeProject, createdAt: Number.parseInt(createdAt, 10), name };
    })
    // An object with no parseable creation label has an unknown age, and this
    // sweep never removes what it cannot date.
    .filter((object) => object.name !== '' && Number.isFinite(object.createdAt));
}

function identifiers(stdout: string): string[] {
  return stdout.split(/\r?\n/).map((line) => line.trim()).filter((line) => line !== '');
}

async function removeComposeProject(command: CommandRunner, project: string, removed: string[]): Promise<void> {
  // Compose labels its own objects with the project rather than with this
  // suite's label, and `compose down` is unusable from a sweep: compose.yaml
  // declares required variables (`${EOW_POSTGRES_PASSWORD:?...}`) whose env file
  // died with the run. Removing by compose's own label is exact and needs no
  // interpolation.
  const projectFilter = ['--filter', `label=${COMPOSE_PROJECT_LABEL}=${project}`];

  // Named rather than by id throughout, so that every object this sweep removes
  // is one whose name carries the suite's prefix -- a property the tests assert,
  // and one an opaque container id would silently give up.
  const containers = await command('docker', ['ps', '-a', ...projectFilter, '--format', '{{.Names}}']);
  for (const container of identifiers(containers.stdout)) {
    const removedContainer = await command('docker', ['rm', '-f', '-v', container]);
    if (removedContainer.exitCode === 0) removed.push(`compose container ${container}`);
  }
  // Volumes and networks only release once their containers are gone.
  const volumes = await command('docker', ['volume', 'ls', ...projectFilter, '--format', '{{.Name}}']);
  for (const volume of identifiers(volumes.stdout)) {
    const removedVolume = await command('docker', ['volume', 'rm', volume]);
    if (removedVolume.exitCode === 0) removed.push(`compose volume ${volume}`);
  }
  const networks = await command('docker', ['network', 'ls', ...projectFilter, '--format', '{{.Name}}']);
  for (const network of identifiers(networks.stdout)) {
    const removedNetwork = await command('docker', ['network', 'rm', network]);
    if (removedNetwork.exitCode === 0) removed.push(`compose network ${network}`);
  }
}

/**
 * Removes fixture objects left by a run that never reached `afterEach` -- a
 * killed worker, an interrupted run, a rebooted machine. Runs at the start and
 * the end of every vitest run for this package, so a run that was killed outright
 * is cleaned up by the next one rather than accumulating.
 */
export async function sweepStaleFixtures(
  command: CommandRunner = run,
  now: number = Date.now(),
  maximumAgeMs: number = STALE_FIXTURE_AGE_MS,
): Promise<string[]> {
  const removed: string[] = [];
  const labelFilter = ['--filter', `label=${FIXTURE_LABEL}=1`];

  let containers: CommandResult;
  try {
    containers = await command('docker', [
      'ps', '-a', ...labelFilter,
      '--format', `{{.Names}}\t{{.Label "${FIXTURE_CREATED_LABEL}"}}\t{{.Label "${COMPOSE_PROJECT_LABEL}"}}`,
    ]);
  } catch {
    return removed; // No Docker CLI at all: nothing this suite owns can be running.
  }
  if (containers.exitCode !== 0) return removed;

  const composeProjects = new Set<string>();
  for (const container of parseLabelledObjects(containers.stdout)) {
    if (now - container.createdAt < maximumAgeMs) continue;
    // -v is what reclaims the container's anonymous PGDATA volume. Without it a
    // removed container still leaves its ~50 MB of postgres data behind, once
    // per fixture -- which is how this suite accumulated 1039 dangling volumes
    // worth 49 GB without a single test ever failing.
    const removedContainer = await command('docker', ['rm', '-f', '-v', container.name]);
    if (removedContainer.exitCode === 0) removed.push(`container ${container.name}`);
    if (container.composeProject !== '') composeProjects.add(container.composeProject);
  }
  for (const project of composeProjects) await removeComposeProject(command, project, removed);

  // Networks are swept by name rather than by label: an idle one costs nothing
  // to remove, Docker refuses while a container still attaches it, and the name
  // reaches orphans from runs that predate the labels. No age gate is needed for
  // the same reason -- a live fixture's network is never idle.
  const networks = await command('docker', [
    'network', 'ls', '--filter', `name=^${FIXTURE_NAME_PREFIX}`, '--format', '{{.Name}}',
  ]);
  if (networks.exitCode === 0) {
    for (const network of identifiers(networks.stdout)) {
      const removedNetwork = await command('docker', ['network', 'rm', network]);
      if (removedNetwork.exitCode === 0) removed.push(`network ${network}`);
    }
  }

  // A Compose fixture killed between losing its containers and removing its
  // volumes leaves the project's named volume with no labelled container left to
  // find it through. Compose stamps the project on the volume, and only this
  // suite generates that prefix, so this cannot reach the workspace's own stack.
  const composeVolumes = await command('docker', [
    'volume', 'ls', '--filter', `label=${COMPOSE_PROJECT_LABEL}`,
    '--format', `{{.Name}}\t{{.Label "${COMPOSE_PROJECT_LABEL}"}}`,
  ]);
  if (composeVolumes.exitCode === 0) {
    for (const line of identifiers(composeVolumes.stdout)) {
      const [name = '', project = ''] = line.split('\t');
      if (name === '' || !project.startsWith(COMPOSE_PROJECT_PREFIX) || composeProjects.has(project)) continue;
      const removedVolume = await command('docker', ['volume', 'rm', name]);
      if (removedVolume.exitCode === 0) removed.push(`compose volume ${name}`);
    }
  }

  return removed;
}
